version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'artale'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/mysql/db/:/var/lib/mysql
      - ./data/mysql/initdb.d/:/docker-entrypoint-initdb.d/
      - ./data/mysql/conf.d/:/etc/mysql/conf.d/
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"